### ISSUE TITLE
Incompatibility doctrine orm module ^2.1

### ISSUE THREAD

**Issue by gabrovex** [salesupply/zf-doctrine-encrypt-module#14]
please upgrade to "doctrine/doctrine-orm-module": "^2.1",

**Comment by rkeet** [comment]
Thanks for reporting. Have gotten it started. Should have more info and/or an update by week's end.

**Comment by rkeet-salesupply** [comment]
Module being deprecated - use https://github.com/rkeet/zf-doctrine-encrypt instead
